### ISSUE TITLE
有关output stationary逻辑的疑问

### ISSUE THREAD

**Issue by KingRayCao** [pku-liang/hlcd-spmm-project#14]
请问在此次project中，output stationary的逻辑是如下的吗：
在完成一次output计算并存储到buffer后，如果out_start不使能，则lhs_ready_os一直激活，直到lhs_start并且lhs_os为真（此时把buffer中数据拿到下一组中计算）或者out_start为真（此时开启输出）。
那如果下一次lhs_start且lhs_os为假，那这次的结果直接丢弃吗？还是继续保留？
麻烦您提供一下lhs_os的示例，将各种组合情况更为清楚的规约一下，谢谢！

**Comment by KEKE046** [comment]
可以看 https://github.com/pku-liang/hlcd-spmm-project/issues/13#issuecomment-2558351734
