### ISSUE TITLE
对于评分判定的疑问

### ISSUE THREAD

**Issue by KingRayCao** [pku-liang/hlcd-spmm-project#17]
请问最终判断效果时，允许中间多几个缓冲的时间周期吗？比如有double buf的RHS，但是连续两次读之间空了一拍？

**Comment by KEKE046** [comment]
允许的，会有十几个周期的 tolerance。

**Comment by KingRayCao** [comment]
好的。顺便问一下，允许always_ff @(posedge lhs_start)这种写法吗？

**Comment by KEKE046** [comment]
允许
