### ISSUE TITLE
有关最终测试数据的疑问

### ISSUE THREAD

**Issue by KingRayCao** [pku-liang/hlcd-spmm-project#19]
现在所给的测试数据样本较少，很可能存在漏洞，是否可能在12.27的测试中多运行一些最终评测会使用的数据，并开放部分失败的数据点？

**Comment by KEKE046** [comment]
会。评测数据中，OS/WS/NS 的基本模式不会变，主要变动的是稀疏矩阵的格式和 tiling 的方式。
