### ISSUE TITLE
PE测试样例中lhs_start激活时间不统一

### ISSUE THREAD

**Issue by KingRayCao** [pku-liang/hlcd-spmm-project#2]
在运行```make N=4 PE```时，03 04 06 07 10和其他测试样例中```lhs_start```激活时间不统一，前者全程有效，而后者只激活一个周期。
如图：
01：
![image](https://github.com/user-attachments/assets/81257579-7d41-4030-bacc-6ce9c232de77)
03：
![image](https://github.com/user-attachments/assets/2f675222-e664-4788-afdb-961fe9e2411b)

**Comment by KingRayCao** [comment]
已拉取最新版本，问题仍然存在。

**Comment by KEKE046** [comment]
已经合并了#3，谢谢你
