### ISSUE TITLE
我发现这个SpMM中dut->send_rhs(rhs1); dut->step();连续执行了tick,导致我观察不到rhs_start

### ISSUE THREAD

**Issue by wwwqwq2022** [pku-liang/hlcd-spmm-project#21]
![屏幕截图 2024-12-24 160341](https://github.com/user-attachments/assets/b8bd85ec-91ad-430b-8241-6f26546167db)

**Comment by wwwqwq2022** [comment]
![屏幕截图 2024-12-24 160546](https://github.com/user-attachments/assets/d5a8d988-8f0d-4e50-9185-0b9c4c96655c)
最后看见的就都是0了

**Comment by KEKE046** [comment]
这个是因为 send_lhs 的时候，需要等待 lhs_ready 为高才能发出去，但波形里没有 lhs_ready_xx 为高的情况，所以会一直等待。

**Comment by KEKE046** [comment]
参考 #42
