### ISSUE TITLE
spmm gtkwave中无法观察到rhs_data

### ISSUE THREAD

**Issue by wwwqwq2022** [pku-liang/hlcd-spmm-project#22]
为什么spmm gtkwave中无法观察到rhs_data
![屏幕截图 2024-12-24 193908](https://github.com/user-attachments/assets/e1fe5545-6ddb-4c2b-ab7b-98a6669fa728)
r如图所示，我用rhs过滤了之后没看到data

**Comment by KEKE046** [comment]
这个 tb 没有加 rhs_data，你可以手动加上，也可以仿造另外两个 tb 在 `generate_gtkw_file` 函数里添加相关的语句：

https://github.com/pku-liang/hlcd-spmm-project/blob/7625fe43b5bb92b54657931ab1b6ff494af96b66/SpMM.tb.cpp#L262-L278

https://github.com/pku-liang/hlcd-spmm-project/blob/7625fe43b5bb92b54657931ab1b6ff494af96b66/PE.tb.cpp#L274-L287
