### ISSUE TITLE
关于lhs_ptr的疑问

### ISSUE THREAD

**Issue by Friedrichqi** [pku-liang/hlcd-spmm-project#24]
![image](https://github.com/user-attachments/assets/5f661bc0-cd6b-4210-9d50-64c6332a115a)
lhs_ptr的定义是记录每一行的结束元素所在位置。我不太理解它为何会超过N-1。是不是比如N=31就是第二个周期输入的lhs_data在comlumn=15处截断。这里是为了我们做60分部分debug方便，还是以后的数据都是这样呈现的(lhs_ptr会超过N-1)呢？

**Comment by KEKE046** [comment]
lhs_ptr 一般都会超过 $N-1$，它的范围是 $[0,N^2)$。你可以再看一下 README 中的例子，lhs_ptr 指向的是每一行第一个元素的位置，这个“位置”指的是将矩阵 flatten 成一个 COO 之后，每一行第一个元素的下标。
![image](https://github.com/user-attachments/assets/f374a86e-e3e3-4d27-8776-15468c2106f8)

**Comment by Friedrichqi** [comment]
谢谢
