### ISSUE TITLE
关于start信号posedge位置的疑问

### ISSUE THREAD

**Issue by shiki-mkh** [pku-liang/hlcd-spmm-project#25]
![屏幕截图 2024-12-25 192420](https://github.com/user-attachments/assets/432444c2-650b-446d-a5d8-cd3800abbbbd)
如图，请问在测试数据中lhs_start信号的posedge是否都和clock的posedge错开？
假如lhs_start和时钟的posedge同时发生，那么在posedge clock读入lhs_ptr用于计算split和out_idx（采用时序逻辑），但同时lhs_data传入redunit，所以这种情况可能造成split和lhs的错位？

**Comment by KEKE046** [comment]
这个 lab 中应该没有任何异步的逻辑，任何 `xx_start` 都是在 posedge 被采样的。

**Comment by shiki-mkh** [comment]
那我是否可以在posedge lhs_start（图中虚线） 进行split的计算，这样在下个posedge clock之前得到正确的split值并和lhs_data一起传入redunit进行计算呢

**Comment by KEKE046** [comment]
不保证正确性

**Comment by KEKE046** [comment]
实际可能基本都是对的

**Comment by shiki-mkh** [comment]
感谢
