### ISSUE TITLE
02-rhs-dbbuf测试中出现timeout的情况

### ISSUE THREAD

**Issue by AstroCIEL** [pku-liang/hlcd-spmm-project#26]
![image](https://github.com/user-attachments/assets/f0ab6d3d-94fb-4cb6-8918-f151cff8956c)
在02-rhs-dbbuf测试中，出现了timeout的情况，请问是什么原因引起的呢

**Comment by KEKE046** [comment]
rhs dbbuf 的测试方法是先读入两个 rhs 矩阵，再读入 lhs 矩阵。在你的波形里面似乎只输入了一个 rhs 矩阵，可以看 #4，https://github.com/pku-liang/hlcd-spmm-project/issues/13#issuecomment-2558351734
