### ISSUE TITLE
Redunit.tb一定要按照写好的规则来吗

### ISSUE THREAD

**Issue by YokoiWing** [pku-liang/hlcd-spmm-project#28]
各个模块单元的tb一定要求通过吗，还是只要输入输出的逻辑自洽最后总的tb能过就行？

**Comment by KEKE046** [comment]
要求通过，考虑到可能有同学是过不了最后的 tb 的，模块 tb 可以防止没有期末 lab 没有分数。

**Comment by feiyunzhisahng** [comment]
那如果我把PE的testbench都过了（PE例化RedUnit），但是RedUnit的tb没过可以吗？
这样的原因是：我把Halo adder实现Redunit里更方便，Halo是考虑前后关系的，但是redunit的测试样例是不考虑前后输入头尾和相加的。

**Comment by feiyunzhisahng** [comment]
我已经通过增加信号解决了这个问题，学长可以忽略我的问题
