### ISSUE TITLE
tb接收到的out矩阵是否需要转置？

### ISSUE THREAD

**Issue by AstroCIEL** [pku-liang/hlcd-spmm-project#29]
![image](https://github.com/user-attachments/assets/ac7c5b61-f8dc-41bd-9d45-ae8ede697814)
我发现我输出的矩阵总是和expected有转置的关系。spmm顶层模块中规定了输出信号out_data是4xN的形状，而这应该是转置之后的结果。将这个转置之后的结果赋给了tb中的out，导致最后的结果是转置的。我不知道是不是我理解上出了什么问题？

**Comment by KEKE046** [comment]
读入的 RHS 矩阵是没有转置的，一次会读 4 行，而不是 4 列。输出矩阵也是没有转置的，一次输出 4 行，而不是 4 列。
