### ISSUE TITLE
关于PE输入矩阵lhs_data的疑问

### ISSUE THREAD

**Issue by Friedrichqi** [pku-liang/hlcd-spmm-project#30]
您好，想问一下如果像测试样例中的empty那组数据，输入除了第一行之外全是0，那么是不是应该除了T=1的时候有输入，其他时候全是0这样子。但是为什么我们的testbench输入好像输入0200之后就维持不变了呢。
![image](https://github.com/user-attachments/assets/953eb738-313f-4915-a2cf-662158960988)
![image](https://github.com/user-attachments/assets/8a9a03b1-4147-4302-b752-1225061993bd)

**Comment by KEKE046** [comment]
在输入 start 的周期，输入就已经立刻完成了，后面的输入都是无效的，所以可以为任意值。

**Comment by Friedrichqi** [comment]
谢谢
