### ISSUE TITLE
rdu.tb 在 lhs某一行为空的情况下 的 处理方式

### ISSUE THREAD

**Issue by shiki-mkh** [pku-liang/hlcd-spmm-project#35]
在rdu.tb中,out_idx的值是完全随机的，而在实际情况输入lhs是逐行输入，所以out_idx是递增的，这可能带来如下问题：
如果lhs_ptr[i]==lhs_ptr[i-1],那么会有out_idx[i]==out_idx[i-1]，在rdu中out_data一个部分和就被取了两次，累加的时候出现错误。
要解决这个问题可以增加out_idx的位宽、增加valid数组、增加mask等方式，但它们会带来delay变大或是与rdu.tb不兼容的问题：
1）增加位宽可能在tb检测out_idx出问题
2）valid、mask需要由PE生成，单独测rdu的时候没法生成
该如何解决这个兼容性问题

**Comment by KEKE046** [comment]
由 PE 生成，rdu 只管算部分和

**Comment by shiki-mkh** [comment]
好的，感谢
