### ISSUE TITLE
请问output_start信号只要检测到output_ready，就会拉高吗？

### ISSUE THREAD

**Issue by feiyunzhisahng** [pku-liang/hlcd-spmm-project#36]
现在的testbench里的receive out函数应该是这样的，后面会不会人为增加难度创造阻塞而修改成延后一点给

**Comment by KEKE046** [comment]
可能会

**Comment by feiyunzhisahng** [comment]
按照现在的testbench,out_ready（lhs_ready,rhs_ready）等ready信号置为1都只需要保持一个周期，那这种情况需要把out_ready修改成持续拉高直到out_start来吗？

**Comment by KEKE046** [comment]
需要，但第一次测试中不会考虑
