### ISSUE TITLE
请问PE的数量是否一定等于4？

### ISSUE THREAD

**Issue by AgentOracle** [pku-liang/hlcd-spmm-project#37]
如果PE数量限定为必须等于4，那么LHS似乎也需要使用buffer。是否允许将其SpMM进行spatial unroll，使其成为N个PE组成的阵列？

**Comment by DFruoyue** [comment]
PE的数量是 $N$ （列）

**Comment by DFruoyue** [comment]
> 如果PE数量限定为必须等于4，那么LHS似乎也需要使用buffer。是否允许将其SpMM进行spatial unroll，使其成为N个PE组成的阵列？

PE的数量是 $N$ （列）

**Comment by AgentOracle** [comment]
好的，感谢！
