### ISSUE TITLE
RHSdbbuf 和 OUTdbbuf 的工作流程是什么？

### ISSUE THREAD

**Issue by DFruoyue** [pku-liang/hlcd-spmm-project#4]
![截屏2024-12-18 19 01 07](https://github.com/user-attachments/assets/f3f69f72-5779-4682-8603-e209621735b1)

如上图，为什么 `spMM/02-rhs-dbbuf.vcd` 中加载完一轮`rhs_data`后，将`lhs_ready` 拉高，`lhs_start`却不响应？是需要加载两轮`rhs_data` 才能计算吗？

**Comment by KEKE046** [comment]
对，因为 rhs 有两个 buffer，实际上放完一个矩阵之后，rhs buffer 还是 ready 的，可以再放下一个矩阵。

tb 里检查 double buffer 的方法，就是看能不能一次性放两个右矩阵，再输入 lhs。
