### ISSUE TITLE
SpM数据表示

### ISSUE THREAD

**Issue by zZzZ9zZ9** [pku-liang/hlcd-spmm-project#6]
假设SPM的第一行所有元素都为0，那么ptr[0]是多少？如果ptr[0]是0的话那不就还是包含了第一个元素？（虽然没有影响测试数据通过，但是感觉表示方法有bug）或者说测试样例里面都保证了SpM第一行一定有一个值？

**Comment by KEKE046** [comment]
是的，保证 SpM 第一行至少有一个值。这是本次 lab 的 spmm 格式的缺陷，第一行不能为空。
这样设计的原因是为了把 ptr fit 到 $2 \log_2 n$ 的位宽。README 中也说到：

https://github.com/pku-liang/hlcd-spmm-project/blob/76bed529d0e93b139fb3e439fd0b169f784db0da/README.md?plain=1#L29

> 更标准的是记录开始元素，但在这个 lab 里我们考虑结束元素

**Comment by zZzZ9zZ9** [comment]
Thx!
