### ISSUE TITLE
关于FAN和前缀和的RedUnit单元

### ISSUE THREAD

**Issue by zZzZ9zZ9** [pku-liang/hlcd-spmm-project#7]
请问FAN相比于前缀和的优势在哪里呢？延迟上整体都是lgN，RedUnit可能多一个减法的延迟，FAN的面积应该会小一些。最后是怎么分辨这两种方法的？

**Comment by KEKE046** [comment]
FAN 使用的加法器数量少很多。FAN 只需要使用 n 个加法器，而 PfxSum 会使用 nlogn 个加法器。

区分方法是助教看源代码，或者面测时候问，或者跑逻辑综合看加法器数量。

**Comment by KEKE046** [comment]
另，RedUnit 也可以不需要减法，会省一个 cycle

**Comment by zZzZ9zZ9** [comment]
嗯嗯的确，前缀和也有方法可以省略减法操作。
Thx！
