### ISSUE TITLE
有关rhs_start使能时机的疑问

### ISSUE THREAD

**Issue by KingRayCao** [pku-liang/hlcd-spmm-project#8]
请问测试中`out_start`能够保证一检测到`out_ready`就启动吗？
如若不然，如此处的时序图：

> [1b23e73](https://github.com/pku-liang/hlcd-spmm-project/commit/1b23e738b9cbafbe96b48bfb5dea0b2e1be188a2) 里放了一个 WS 的时序图
> 
> ![](https://camo.githubusercontent.com/ea9cef7179e4692cd4c0081428fed6451e7f6f23902b24fcffd78d69badc1434/68747470733a2f2f7376672e7761766564726f6d2e636f6d2f6769746875622f706b752d6c69616e672f686c63642d73706d6d2d70726f6a6563742f666139666662313230373933643364636361663731306636396236633736643164653834333839392f666967732f70652d61727261792d7773322e6a736f6e35)

假设`out_start`一直不使能，则模块需要一直存储着第一次`out`结果。但是前期输入了三组`lhs`数据（此时无法预知后续`out_start`情况），即使是`double buffer`也无法存储三组`out`输出。
而如果能够保证这一点，则在时序上后输入的`lhs`所产生的结果一定严格在前输入的`lhs`之后，应该不需要`double buffer`？

**Comment by KEKE046** [comment]
out_start 可能一直不使能，这样会阻塞，导致 lhs 和 rhs 都不能 ready

**Comment by KingRayCao** [comment]
那这样的话上面的样例不是有问题吗？在`lhs_os`未使能时，不能一次性读三个lhs进来

**Comment by KEKE046** [comment]
确实，这幅图可能有问题，你可以认为中间有 output stationary，我可以改一下，把 out 往前拖一点

**Comment by KEKE046** [comment]
ab21921 中修改了时序图

![](https://svg.wavedrom.com/github/pku-liang/hlcd-spmm-project/ab219214ca58e74cbf3e994bccc553853c5453bf/figs/pe-array-ws3.json5)

**Comment by KEKE046** [comment]
如果没有问题，我把 issue 关闭了
