### ISSUE TITLE
WSPipe测试点：波形和仿真文件不对应

### ISSUE THREAD

**Issue by Gracfusie** [pku-liang/hlcd-spmm-project#9]
![1734681420594](https://github.com/user-attachments/assets/beb3ed61-3995-4792-9f28-104b9a271769)
ws-pipe例子中，有2个rhs，每个rhs计算一个标记ws的lhs和一个标记ns的lhs，但是在仿真波形中有两个信号没反应
（1）虽然提供了rhs_ready信号，没有第二个**rhs_start**出现；
（2）第一个lhs理应带着ws标记，但是**lhs_ws**为信号始终为低

**Comment by KEKE046** [comment]
原因是代码 send lhs 之后没有等待一个周期，已经修复
